# 基础服务配置 - 数据库、Redis等共享服务
# version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: visitor-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: visitor_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres123}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./visitorSystem-backend/prisma/migrations:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - visitorsystem-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: visitor-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redis123}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - visitorsystem-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # 数据库管理工具 (可选)
  adminer:
    build:
      context: .
      dockerfile: docker/adminer/Dockerfile
    image: visitorsystem-adminer:latest
    container_name: visitor-adminer
    restart: unless-stopped
    ports:
      - "8089:8089"
    networks:
      - visitorsystem-network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  visitorsystem-network:
    external: true
