# 蓝环境应用配置
version: '3.8'

services:
  # 蓝环境后端服务
  backend-blue:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: visitor-backend-blue
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD:-postgres123}@postgres:5432/visitor_system
      - REDIS_URL=redis://:${REDIS_PASSWORD:-redis123}@redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis123}
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - WHATSAPP_API_KEY=${WHATSAPP_API_KEY}
      - WHATSAPP_PHONE_NUMBER=${WHATSAPP_PHONE_NUMBER}
    ports:
      - "3001:3001"
    networks:
      - visitorsystem-network
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "node", "health-check.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 蓝环境前端服务
  frontend-blue:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        # ✅ 使用相对路径，通过外部Nginx代理
        - VITE_API_BASE_URL=${VITE_API_BASE_URL:-/api}
        - NODE_ENV=${NODE_ENV:-production}
        # ✅ 防缓存参数：每次构建都会变化
        - BUILD_TIMESTAMP=${BUILD_TIMESTAMP:-$(date +%s)}
    container_name: visitor-frontend-blue
    restart: unless-stopped
    ports:
      - "3002:3002"  # 映射到内部3002端口
    networks:
      - visitorsystem-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  visitorsystem-network:
    external: true